# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget # PlotWidget 임포트가 맨 아래에서 위로 이동


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 800)
        
        # NOTE: Form 대신 QMainWindow를 사용하려면 클래스 이름을 Ui_MainWindow로 변경하고,
        # self.ui = Ui_MainWindow()를 사용해야 main_controller와 호환됩니다.
        # 현재는 Ui_Form에 맞게 코드를 유지합니다.

        self.widget_6 = QtWidgets.QWidget(Form)
        self.widget_6.setGeometry(QtCore.QRect(100, 60, 491, 311))
        self.widget_6.setObjectName("widget_6")
        
        # graph_1S를 QChartView에서 PlotWidget으로 변경
        self.graph_1S = PlotWidget(self.widget_6)
        self.graph_1S.setGeometry(QtCore.QRect(19, 49, 451, 241)) # 이전에 frame_batt1의 영역을 사용
        self.graph_1S.setObjectName("graph_1S")

        # 기존 frame_batt1 위젯은 graph_1S의 크기와 겹치거나 필요 없을 수 있어 임시로 주석 처리
        # self.frame_batt1 = PlotWidget(self.widget_6) 
        # self.frame_batt1.setGeometry(QtCore.QRect(19, 49, 451, 241))
        # self.frame_batt1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.frame_batt1.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.frame_batt1.setObjectName("frame_batt1")


        self.widget_7 = QtWidgets.QWidget(Form)
        self.widget_7.setGeometry(QtCore.QRect(700, 60, 491, 311))
        self.widget_7.setObjectName("widget_7")
        
        # graph_2S를 QChartView에서 PlotWidget으로 변경
        self.graph_2S = PlotWidget(self.widget_7)
        self.graph_2S.setGeometry(QtCore.QRect(19, 49, 451, 241))
        self.graph_2S.setObjectName("graph_2S")
        
        # 기존 frame_batt2 위젯은 임시 주석 처리
        # self.frame_batt2 = PlotWidget(self.widget_7)
        # self.frame_batt2.setGeometry(QtCore.QRect(19, 49, 451, 241))
        # self.frame_batt2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.frame_batt2.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.frame_batt2.setObjectName("frame_batt2")


        self.widget_8 = QtWidgets.QWidget(Form)
        self.widget_8.setGeometry(QtCore.QRect(100, 410, 491, 311))
        self.widget_8.setObjectName("widget_8")

        # graph_3S를 QChartView에서 PlotWidget으로 변경
        self.graph_3S = PlotWidget(self.widget_8)
        self.graph_3S.setGeometry(QtCore.QRect(19, 49, 451, 241))
        self.graph_3S.setObjectName("graph_3S")
        
        # 기존 frame_batt3 위젯은 임시 주석 처리
        # self.frame_batt3 = PlotWidget(self.widget_8)
        # self.frame_batt3.setGeometry(QtCore.QRect(19, 49, 451, 241))
        # self.frame_batt3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.frame_batt3.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.frame_batt3.setObjectName("frame_batt3")


        self.widget_9 = QtWidgets.QWidget(Form)
        self.widget_9.setGeometry(QtCore.QRect(700, 410, 491, 311))
        self.widget_9.setObjectName("widget_9")
        
        # graph_Total를 QChartView에서 PlotWidget으로 변경
        self.graph_Total = PlotWidget(self.widget_9)
        self.graph_Total.setGeometry(QtCore.QRect(19, 49, 451, 241))
        self.graph_Total.setObjectName("graph_Total")
        
        # 기존 frame_batt_total 위젯은 임시 주석 처리
        # self.frame_batt_total = PlotWidget(self.widget_9)
        # self.frame_batt_total.setGeometry(QtCore.QRect(19, 49, 451, 241))
        # self.frame_batt_total.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.frame_batt_total.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.frame_batt_total.setObjectName("frame_batt_total")


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
# 이전에 있던 잘못된 'from qchartview import QChartView' 라인 삭제됨.

# pyqtgraph 임포트가 클래스 정의 전에 위치하도록 이동 (main_controller와 일치시킴)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())